local custom_fns = require('custom_functions')
local opts = { noremap = true, silent = true }

local M = {}

function M.apply_keymaps()
  local peek = require('peek')
  vim.keymap.set('n', 'Q', ':q<CR>', opts)
  vim.keymap.set('n', 'W', ':wa<CR>', opts)
  vim.keymap.set('n', '<C-s>', ':w<CR>', opts)
  vim.keymap.set('n', '<C-n>', ':vnew<CR>', opts)
  vim.keymap.set('n', '<A-n>', ':new<CR>', opts)
  vim.keymap.set('n', '<C-t>', ':tabnew<CR>', opts)
  vim.keymap.set('n', '<A-t>', ':terminal<CR>', opts)
  vim.keymap.set('n', '<A-h>', '<C-w><left>', opts)
  vim.keymap.set('n', '<A-j>', '<C-w><down>', opts)
  vim.keymap.set('n', '<A-k>', '<C-w><up>', opts)
  vim.keymap.set('n', '<A-l>', '<C-w><right>', opts)
  vim.keymap.set('n', '<left>', '<C-w><left>', opts)
  vim.keymap.set('n', '<down>', '<C-w><down>', opts)
  vim.keymap.set('n', '<up>', '<C-w><up>', opts)
  vim.keymap.set('n', '<right>', '<C-w><right>', opts)
  vim.keymap.set('n', '<A-,>', ':tabprevious<CR>', opts)
  vim.keymap.set('n', '<A-.>', ':tabnext<CR>', opts)
  vim.keymap.set('n', '<F1>', '<cmd>Telescope help_tags<CR>', opts)
  vim.keymap.set('n', '<F2>', '<cmd>Telescope registers<CR>', opts)
  vim.keymap.set('n', '<F3>', '<cmd>Telescope buffers<CR>', opts)
  vim.keymap.set('n', '<F4>', '<cmd>Telescope live_grep<CR>', opts)
  vim.keymap.set('n', '<F5>', '<cmd>Telescope colorscheme<CR>', opts)
  vim.keymap.set('n', '<S-F5>', ':edit<CR>', opts)
  vim.keymap.set('n', '<F6>', '<cmd>Telescope file_browser<CR>', opts)
  vim.keymap.set('n', '<F7>', '<cmd>Telescope current_buffer_fuzzy_find<CR>', opts)
  vim.keymap.set('n', '<F8>', '<cmd>Telescope notify<CR>', opts)
  vim.keymap.set('n', '<F9>', ':NvimTreeToggle<CR>', opts)
  vim.keymap.set('n', '<F10>', ':SymbolsOutline<CR>', opts)
  vim.keymap.set('n', '<F11>', ':terminal<CR>')
  vim.keymap.set('n', '<F12>', '<cmd>Telescope lsp_definitions<CR>', opts)
  vim.keymap.set('n', '<leader><F1>', '<cmd>Telescope git_status<CR>', opts)
  vim.keymap.set('n', '<leader><F2>', '<cmd>Telescope git_stash<CR>', opts)
  vim.keymap.set('n', '<leader><F3>', '<cmd>Telescope git_branches<CR>', opts)
  vim.keymap.set('n', '<leader><F4>', '<cmd>Telescope git_commits<CR>', opts)
  vim.keymap.set('n', '<leader><F5>', ':edit<CR>', { noremap = true })
  vim.keymap.set('n', '<leader><F8>', ':messages<CR>', opts)
  vim.keymap.set('n', '<leader>ff', '<cmd>Telescope find_files<CR>', opts)
  vim.keymap.set('n', '<leader>fg', '<cmd>Telescope live_grep<CR>', opts)
  vim.keymap.set('n', '<leader>fb', '<cmd>Telescope buffers<CR>', opts)
  vim.keymap.set('n', '<leader>fh', '<cmd>Telescope help_tags<CR>', opts)
  vim.keymap.set('n', '<leader>1', ':colorscheme onedarkpro<CR>', opts)
  vim.keymap.set('n', '<leader>2', ':colorscheme oh-lucy<CR>', opts)
  vim.keymap.set('n', '<leader>3', ':colorscheme oh-lucy-evening<CR>', opts)
  vim.keymap.set('n', '<leader>4', ':colorscheme adwaita<CR>', opts)
  vim.keymap.set('n', '<leader>5', ':colorscheme seoul256<CR>', opts)
  vim.keymap.set('n', '<leader>ev', ':tabnew $MYVIMRC<CR>', opts)
  vim.keymap.set('n', '<leader><F5>', custom_fns.refresh_config, opts)
  vim.keymap.set('n', '<leader>r', ':edit<CR>', opts)
  vim.keymap.set('n', '<leader>h', ':noh<CR>', opts)
  vim.keymap.set('n', '<leader>w', ':w<CR>', opts)
  vim.keymap.set('n', '<leader>q', ':q<CR>', opts)
  vim.keymap.set('n', '<leader>km', ':edit ~/dotfiles/.config/nvim/lua/key_mappings.lua<CR>', opts)
  vim.keymap.set('n', '<Tab>', ':NvimTreeFindFile<CR>', opts)
  vim.keymap.set('i', 'jj', '<Esc>', opts)
  vim.keymap.set('i', 'jk', '<Esc>:w<CR>', opts)
  vim.keymap.set('i', '<A-BS>', '<cmd>:execute "normal! db"<CR>', opts)
  vim.keymap.set('i', '<A-,>', '<Esc>:tabprevious<CR>', opts)
  vim.keymap.set('i', '<A-.>', '<Esc>:tabnext<CR>', opts)
  vim.keymap.set('n', '<Leader>cb', custom_fns.clear_bg_color, opts)
  vim.keymap.set('n', '<Leader>tt', custom_fns.toggle_theme, opts)
  vim.keymap.set('n', '<Leader>json=', custom_fns.buf_format_json, opts)
  vim.keymap.set('n', '<Leader>p', peek.open, opts)
  vim.keymap.set('n', '<Leader>P', peek.close, opts)

  -- terminal mode, switch to normal mode.
  vim.keymap.set('t', '<Esc>', '<C-\\><C-n>', opts)
end

function M.create_user_commands()
  -- found a better way to do this, but keeping them around for later reference.
  -- vim.api.nvim_create_user_command('PeekOpen', require('peek').open, {})
  -- vim.api.nvim_create_user_command('PeekClose', require('peek').close, {})
end

return M

