#!/bin/sh
#
# switch-mon

case $1 in
  "internal")
    export XORG_DPI=140
    echo Xft.dpi: $XORG_DPI | xrdb
    bspc monitor eDP-1 -d I II III IV V VI VII
    source ~/dotfiles/.screenlayout/framework-int.sh
    source ~/dotfiles/scripts/dpi 140
  ;;
  "external")
    ruby ~/dotfiles/scripts/activate-display.rb
  ;;
  "dual")
    echo nothing yet!
    notify-send \
      --urgency=critical \
      --expire-time 2000 \
      "no dual monitor config yet!"
  ;;
  "off")
    xrandr \
      --output eDP-1 --off \
      --output DP-1 --off \
      --output DP-2 --off \
      --output DP-3 --off \
      --output DP-4 --off
  ;;
esac

