#!/bin/sh
#
# bspwmrc

EXT_MON=$(xrandr -q | grep '^DP-[1-9] connected')
echo $EXT_MON

if [[ $EXT_MON ]]
then
  MON=$(echo $EXT_MON | cut -d ' ' -f 1)
  echo bspwm setup for eDP-1 and $MON
  bspc monitor $MON -d I II III IV V VI VII
  bspc monitor eDP-1 -d a b c d e
else
  echo bspwm setup for eDP-1
  bspc monitor eDP-1 -d I II III IV V VI VII
fi

bspc config border_width         3
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config automatic_scheme longest_side

# RULES
#
# a quick hint for finding window names:
# https://www.reddit.com/r/bspwm/comments/fqpvx0/comment/flrof4s

bspc rule -a Zathura state=tiled
bspc rule -a Deno state=tiled
bspc rule -a Pavucontrol state=tiled
bspc rule -a firefox desktop="I" follow=off focus=off
bspc rule -a whatsdesk desktop="VII" follow=off focus=off
bspc rule -a discord desktop="VII" follow=off focus=off

source $HOME/dotfiles/.config/bspwm/bspwmrc-theme

