#! /bin/sh
#
# bspwmrc

if [[ $(xrandr -q | grep -w "DP-3 connected") ]]
then
  bspc monitor DP-3 -d I II III IV V
  bspc monitor eDP-1 -d VI VII VIII IX X
elif [[ $(xrandr -q | grep -w "HDMI-1 connected") ]]
then
  bspc monitor HDMI-0 -d I II III IV V
  bspc monitor eDP-1 -d VI VII VIII IX X
else
  bspc monitor eDP-1 -d I II III IV V
fi

bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme longest_side
# bspc config automatic_scheme spiral

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# RULES
#
# a quick hint for finding window names:
# https://www.reddit.com/r/bspwm/comments/fqpvx0/comment/flrof4s/?utm_source=share&utm_medium=web2x&context=3

bspc rule -a Zathura state=tiled
bspc rule -a Deno state=tiled

source $HOME/dotfiles/.config/bspwm/bspwmrc-theme

