#!/usr/bin/env fish
# vi: set ts=2 sw=2:
# requires https://github.com/baskerville/xwinfo

set wid $argv[1]
set class $argv[2]
set instance $argv[3]
set consequences $argv[4]

eval $consequences

switch "$class"
  case firefox
    switch "$instance"
      case firefox
        switch (xwinfo -t $wid)
          case dialog
            printf 'state=floating\n'
          case '*'
            printf 'state=pseudo_tiled\n'
        end
    end
end
