#!/bin/sh
#
# bspeww.sh

BSPEWW_DIR=/tmp

function node_callback() {
  echo $1 >> $BSPEWW_DIR/bspeww.log
 
  # dump the bspwm world state and pipe it to jq.
  # recursively grab all node names (open programs)
  # for each desktop, concatenate them, and assign
  # them to an array. honestly i don't know how the
  # jq functions work. chatgpt is the real hero here.
  bspc wm -d \
    | jq -c '.monitors[].desktops[] | .root // {} | [.[] | recurse | select(.className?) | .className]' \
    | jq -c -s . \
    | tr '[:upper:]' '[:lower:]' \
    &>> $BSPEWW_DIR/bspeww.json
}

function desktop_callback() {
  echo $1 >> $BSPEWW_DIR/bspeww.log

  # parse the currently selected desktop node from wmtrl -d and write to disk.
  wmctrl -d | grep -F '*' | rev | cut -d ' ' -f 1 | rev >> $BSPEWW_DIR/bspeww.desktop
}

# --- start ---

# kill any prior running services
pkill --echo --full "^bspc\s+subscribe(\s+node_(add|remove|transfer)){3,}"
pkill --echo --full "^bspc\s+subscribe\s+desktop_focus"

mkdir -p $BSPEWW_DIR

# wait for bspwm to start
until [ -S "/tmp/bspwm_0_0-socket" ];
do
  sleep 1.0
done

bspc subscribe node_add node_remove node_transfer | while read line
do
  node_callback "$line"
done &

bspc subscribe desktop_focus | while read line
do
  desktop_callback "$line"
done &

node_callback "bspeww init"
desktop_callback "bspeww init"
