#!/bin/sh

record_volume() {
  pactl -f json list \
    | jq -c '.sinks[] | { mute, volume: .volume["front-left"].value_percent }' \
    >> /dev/shm/volume.json
}

case $1 in
  "logout")
    notify-send --expire-time 2500 "logging off!" "user logout in 3, 2, 1!"
    sleep 3s
    pkill -KILL -u elliot
  ;;
  "shutdown")
    notify-send --expire-time 2500 "powering down!" "in 3, 2, 1!"
    sleep 3s
    systemctl poweroff
  ;;
  "suspend")
    notify-send --expire-time 1100 "~*~._.~*zZzZzzZZZzzZzZz*~._.~*~"
    sleep 1s
    systemctl suspend
  ;;
  ("volup")
    amixer -q sset Master 5%+
    record_volume
  ;;n
  ("voldown")
    amixer -q sset Master 5%-
    record_volume
  ;;
  ("mute")
    amixer -q sset Master 1+ toggle
    record_volume
  ;;
  ("setvol")
    record_volume
  ;;
  "wifitoggle")
    if [ `nmcli radio wifi` == "enabled" ]; then
      notify-send "wifi off"
      nmcli radio wifi off
    else
      notify-send "wifi on"
      nmcli radio wifi on
    fi
  ;;
esac

