#!/bin/sh
#
# switch-mon

case $1 in
  "internal")
    export XORG_DPI=140
    echo Xft.dpi: $XORG_DPI | xrdb
    bspc monitor eDP-1 -d I II III IV V VI VII
    source ~/dotfiles/.screenlayout/framework-int.sh
  ;;
  "external")
    export XORG_DPI=96
    echo Xft.dpi: $XORG_DPI | xrdb
    EXT_MON=$(xrandr -q | grep '^DP-[1-9] connected')
    MON=$(echo $EXT_MON | cut -d ' ' -f 1)
    bspc monitor $MON -d I II III IV V VI VII
    source ~/dotfiles/.screenlayout/current
  ;;
  "dual")
    echo nothing yet!
    notify-send \
      --urgency=critical \
      --expire-time 2000 \
      "no dual monitor config yet!"
  ;;
  "off")
    xrandr \
      --output eDP-1 --off \
      --output DP-1 --off \
      --output DP-2 --off \
      --output DP-3 --off \
      --output DP-4 --off
  ;;
esac

