#!/bin/bash
#
# theme

CONFIG_DIR=~/dotfiles/.config

case "$1" in
  "light")
    ln -sfv $CONFIG_DIR/kitty/theme-light.conf $CONFIG_DIR/kitty/theme.conf
    ln -sfv $CONFIG_DIR/bspwm/bspwmrc-light $CONFIG_DIR/bspwm/bspwmrc-theme
    ln -sfv ~/Pictures/wallpapers/bg-light ~/Pictures/wallpapers/bg
  ;;
  "dark")
    ln -sfv $CONFIG_DIR/kitty/theme-dark.conf $CONFIG_DIR/kitty/theme.conf
    ln -sfv $CONFIG_DIR/bspwm/bspwmrc-dark $CONFIG_DIR/bspwm/bspwmrc-theme
    ln -sfv ~/Pictures/wallpapers/bg-dark ~/Pictures/wallpapers/bg
  ;;
esac

# restart bspwm
bspc wm -r

# change kitty colors
kitty @ set-colors -a $CONFIG_DIR/kitty/theme.conf

# set new background image
sh -c $HOME/dotfiles/etc/.fehbg &
