[general]
import = ["~/.config/alacritty/theme.toml"]

[font]
size = 10.0
offset.y = 1

[font.normal]
family = "Cozette"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "Copy"
mouse = "Left"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.90

[cursor.style]
shape = "underline"
