#!/bin/bash

# Set multiple monitor layout
berryc save_monitor 1 0
berryc save_monitor 2 1
berryc save_monitor 3 0
berryc save_monitor 4 1

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 0
berryc title_height      25
berryc top_gap           25

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "false"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Dina-9"
berryc decorate_new "true"

